#docker run -e mongo_uri=coisaany -p 8080:50051 -v ./:/shared/ nginx
version: '3'

services:
  mongo:
    image: mongo:5.0.9-focal
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    restart: always
    volumes:
      - mongodb:/data/db
    user: root

  mongo-express:
    image: mongo-express:1.0.0-alpha
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    restart: always
    depends_on:
      - mongo

volumes:
  mongodb: